// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20200403172212_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelter.Models.Cat", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Breed");

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.HasKey("CatId");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            CatId = 1,
                            Age = 8,
                            Breed = "DS Blue",
                            Gender = "Male",
                            Name = "Mister"
                        },
                        new
                        {
                            CatId = 2,
                            Age = 7,
                            Breed = "DS Dilute Tortie",
                            Gender = "Female",
                            Name = "Eliza Doolittle"
                        },
                        new
                        {
                            CatId = 3,
                            Age = 1,
                            Breed = "DS Grey Tab",
                            Gender = "Female",
                            Name = "Rhubarb"
                        },
                        new
                        {
                            CatId = 4,
                            Age = 12,
                            Breed = "DL Tab",
                            Gender = "Female",
                            Name = "Twitch"
                        },
                        new
                        {
                            CatId = 5,
                            Age = 18,
                            Breed = "DS Black",
                            Gender = "Female",
                            Name = "Awesome"
                        });
                });

            modelBuilder.Entity("AnimalShelter.Models.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Breed");

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.HasKey("DogId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            DogId = 1,
                            Age = 2,
                            Breed = "Pyrador",
                            Gender = "Male",
                            Name = "Murphy"
                        },
                        new
                        {
                            DogId = 2,
                            Age = 10,
                            Breed = "Malamute",
                            Gender = "Female",
                            Name = "Peaches"
                        },
                        new
                        {
                            DogId = 3,
                            Age = 2,
                            Breed = "Burnese Mountain Dog",
                            Gender = "Female",
                            Name = "Bernice"
                        },
                        new
                        {
                            DogId = 4,
                            Age = 6,
                            Breed = "English Mastiff",
                            Gender = "Male",
                            Name = "Wrex"
                        },
                        new
                        {
                            DogId = 5,
                            Age = 18,
                            Breed = "Rat Terrier",
                            Gender = "Male",
                            Name = "Weezer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
